services:
  - type: web
    name: yolov8-api
    env: python
    plan: free

    pythonVersion: 3.10.13

    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000

    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
